### ISSUE TITLE
Criar data package para documentação das fontes de dados do relatório operacional

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#10]
@hslinhares a tarefa aqui é criar um data package contendo a documentação de todos os arquivos que são utilizados como fonte de dados para o Relatório Operacional.

A gente vai utilizar essa documentação pra confirmar se todos os campos do Armazém utilizados no Relatório Operacional estão disponíveis no [Portal de Dados Abertos](https://dados.mg.gov.br/dataset/?tags=Portal+da+Transpar%C3%AAncia) (que já possuem [data packages associados](https://dados.mg.gov.br/dataset/despesa)).

Além disso, vai servir como forma de você se familiarizar com as [especificações frictionless](https://specs.frictionlessdata.io/) que eventualmente vamos utilizar em nossos fluxos. 

Depois de uma breve navegação no [site principal do projeto Frictionless Data](https://frictionlessdata.io/) sugiro você assistir os seguintes vídeos (em ordem):

- [#CodaBr21 - Apresentações Relâmpago - YouTube](https://www.youtube.com/watch?v=JUW60w1jDdM&t=1346s) (somente a minha apresentação)
- [[CKAN] Webinar: Como gerenciar dados abertos utilizando o DPCKAN - YouTube](https://www.youtube.com/watch?v=oTCQX5a9eXY)

E por fim instalar[^1] o pacote python [`frictionless-py`](https://github.com/frictionlessdata/framework#installation) e seguir o tutorial [Basic Examples](https://framework.frictionlessdata.io/docs/basic-examples.html).

[^1]: Se [familiarize](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment) com o conceito e utilização de ambientes virtuais usando o pacote venv

**Comment by hslinhares** [comment]
O relatório operacional é um painel feito no aplicativo  qlikview alimentado por bases  do armazém SIAFI e SIAD em formato xls e.xlsx, atualizadas diariamente.

Por uma questão de limitação do armazém, as bases algumas bases como a de execução orçamentária, precisam ser divididas por mês, sendo o agrupamento das mesmas feito durante a carga pelo aplicativo qlikview.

Como o objetivo deste trabalho é criar um data package das bases, que consiste basicamente em criar título e descrição para os rótulos das colunas, foi utilizado apenas a base de um mês para cada um dos fluxos, uma vez que os rótulos das colunas são idênticos em todos os meses.

Passo a passo:

Após instalar o pacote [`frictionless-py`](https://github.com/frictionlessdata/framework#installation) e seguir o tutorial [Basic Examples](https://framework.frictionlessdata.io/docs/basic-examples.html), principalmente a parte [Describing a Package] (https://framework.frictionlessdata.io/docs/guides/describing-data.html#describing-a-package) o resultado foi o arquivo anexo.

**Comment by fjuniorr** [comment]
> Como o objetivo deste trabalho é criar um data package das bases, que consiste basicamente em criar título e descrição para os rótulos das colunas, foi utilizado apenas a base de um único mês para cada um dos fluxos, uma vez que os rótulos das colunas são idênticos em todos os meses.

De fato pra gente entender o _schema_ (ie. título e descrição para os rótulos das colunas) não precisamos de repetir todos os meses. No entanto, como cada recurso aponta a localização do arquivo de dados, pra gente efetivamente usar esse data package nas nossas _pipelines_ vamos precisar de documentar tudo.

Pra evitar a repetição do _schema_ a gente tem duas alternativas:

1. [Armazenar o table schema em arquivo externo](https://specs.frictionlessdata.io/guides/implementation/#on-dereferencing-and-descriptor-validation)
1. [Inserir múltiplos arquivos na propriedade `path` do recurso](https://specs.frictionlessdata.io/data-resource/#data-in-multiple-files)

Particularmente eu acho a segunda alternativa mais elegante, mas o suporte das ferramentas tende a ser pior. 

Vamos revisitar essa questão criando um data package com a segunda alternativa e testando se as funcionalidades de leitura e validação funcionam para os pacotes [`frictionless-py`](https://github.com/frictionlessdata/frictionless-py) e [`frictionless-r`](https://github.com/frictionlessdata/frictionless-r).

Faz uma leitura do issue https://github.com/transparencia-mg/issues-dadosmg-legado/issues/12 pra solidificar essas questões e depois cria um data package completo no repo https://github.com/splor-mg/roperacional-dados usando um pull request.

**Comment by hslinhares** [comment]
Decidimos pelo fechamento deste issue porque que este projeto vai ser dividido em vários outros.
Serão criados datapackages para cada fluxo de dados do SIAFI e SIAD (Credito, Execução, Cota, Restos a Pagar) ou de outras fontes (reestimativa, programações anuais, e etc.)
