### ISSUE TITLE
Criar conjunto de dados com bases auxiliares descritivas

### ISSUE THREAD

**Issue by carloshob** [splor-mg/atividades#110]
Construir um data package contendo as bases auxiliares dos classificadores, com os respectivos descritivos.

- [x] criar datapackage
- [x] ajustar makefile

**Comment by carloshob** [comment]
Datapackage concluído e rodando.

**Comment by fjuniorr** [comment]
@carloshob link pras coisas que são [referenciadas](https://github.com/splor-mg/dados-aux-classificadores) sempre ajudam!
