### ISSUE TITLE
Pesquisa sobre ferramenta para extração do conteúdo das apresentações pptx

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#114]
## Links

- https://github.com/junegunn/fzf/wiki/examples#searching-file-contents
- https://github.com/phiresky/ripgrep-all/discussions/199
- [Copilot in OneDrive: A New Wave of File Interaction](https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/copilot-in-onedrive-a-new-wave-of-file-interaction/ba-p/4070738) - We're now proud to say that Copilot in OneDrive will begin to roll out in late-April 2024.

**Comment by labanca** [comment]
Script para extrair texto dos arquivos:
```
# Função para extrair texto de um arquivo .pptx
def extrair_texto_pptx(caminho_arquivo):
    dict_slide = {}
    texto_slide = ''
    presentation = Presentation(caminho_arquivo)
    for num_slide, slide in enumerate(presentation.slides):
        for shape in slide.shapes:
            if shape.has_text_frame:
                for paragraph in shape.text_frame.paragraphs:
                    texto_slide += paragraph.text + " "

        dict_slide[num_slide + 1] = texto_slide
        texto_slide = ''

    print(dict_slide)
    return dict_slide
```

Abaixo, o script completo utilizando um container docker para indexar slides no Elastic Search:


```
import os
from pptx import Presentation
from elasticsearch import Elasticsearch
import csv

# Função para extrair texto de um arquivo .pptx
def extrair_texto_pptx(caminho_arquivo):
    dict_slide = {}
    texto_slide = ''
    presentation = Presentation(caminho_arquivo)
    for num_slide, slide in enumerate(presentation.slides):
        for shape in slide.shapes:
            if shape.has_text_frame:
                for paragraph in shape.text_frame.paragraphs:
                    texto_slide += paragraph.text + " "

        dict_slide[num_slide + 1] = texto_slide
        texto_slide = ''

    print(dict_slide)
    return dict_slide

# Função para indexar documentos no Elasticsearch
def indexar_documentos(documentos):
    es = Elasticsearch(["http://localhost:9200"])
    for documento in documentos:
        es.index(index=documento["_index"], id=documento["_id"], body=documento["_source"])


def save_csv(filename, dict):

    with open(filename, 'w', newline='', encoding='utf-8') as arquivo_csv:

            escritor_csv = csv.writer(arquivo_csv)
            
            # Escrever o cabeçalho (opcional)
            escritor_csv.writerow(['num_slide', 'conteúdo_slide'])

            # Escrever os dados do dicionário no arquivo CSV
            for key, value in dict.items():
                escritor_csv.writerow([key, value])


# Pasta contendo os arquivos .pptx
caminho_pasta_data_raw = 'data-raw'

# Lista para armazenar os documentos a serem indexados no elastic search
documentos_para_indexar = []

# Iterar sobre os arquivos .pptx na pasta data-raw
for nome_arquivo in os.listdir(caminho_pasta_data_raw):
    if nome_arquivo.endswith('.pptx'):
        documento = {}
        caminho_arquivo = os.path.join(caminho_pasta_data_raw, nome_arquivo)

        # obtém counteúdo do slide
        dic_slide = extrair_texto_pptx(caminho_arquivo)

        # Salva csv com conteudo dos slides
        save_csv(f"data/{nome_arquivo.split('.')[0]}.csv", dic_slide)

        for num_slide, texto in dic_slide.items():

            documento = {
                "_index": "slides-cofin",
                "_id": f"{nome_arquivo}_{num_slide}",
                "_source": {
                    "numero_slide": num_slide + 1,
                    "texto": texto
                }
            }

        # adiciona documento ao elastic search
        documentos_para_indexar.append(documento)
        print(documento)


# Indexar os documentos no Elasticsearch
indexar_documentos(documentos_para_indexar)
```


Container utilizado:
```
docker pull elasticsearch:8.8.0
```

`Dockerfile do container:  

```
version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
```

**Comment by labanca** [comment]
> * [Copilot in OneDrive: A New Wave of File Interaction](https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/copilot-in-onedrive-a-new-wave-of-file-interaction/ba-p/4070738) - We're now proud to say that Copilot in OneDrive will begin to roll out in late-April 2024.

Isso é incrível. Achei que era somente pra aprimorar a busca dentro de arquivos no onedrive, mas você pode fazer busca generativa.

**Comment by fjuniorr** [comment]
Relato enviado para o Pedro pra fins de monitoramento do projeto com o Felipe:

> [Encontramos](https://github.com/splor-mg/atividades/issues/114) um pacote maduro do python (`python-pptx`) capaz de extrair todo o conteúdo (eg. texto, notas, imagens) de uma apresentação Powerpoint. Fizemos uma pequena prova de conceito que extrai o texto simples e os números do slide de uma apresentação gerando um resultado:
> 
> ```
> slide,content
> 1, COMITÊ DE ORÇAMENTO E FINANÇAS - COFIN 25 de janeiro de 2023 
> 2, TETO DE GASTOS 2023 
> 3,"ANÁLISE DO TETO DE GATOS Margem de expansão, calculada a partir dos parâmetros gerais para o estabelecimento do teto de gastos para 2023: IPCA projetado para 2023, utilizado para corrigir a despesa empenhada em 2022: 5,39%     Despesas que não se enquadram no teto:  serviço da dívida, concessão de empréstimos e financiamentos, aquisição de títulos de capital já integralizados, aquisição de títulos de crédito, transferências constitucionais aos municípios, transferências vinculadas da união, emendas federais, despesas intraorçamentárias, sentenças judiciais e precatórios. "
> ```
> 
> Apesar de simples, após o desenvolvimento do processo de extração do conteúdo para todos os slides isso já permite a exploração de ferramentas de busca em cima deste conteúdo (eg. Editor de Texto, PowerBI, etc). 
> 
> Em termos da extração ainda não sabemos se é possível gerar o [link para o slide no Sharepoint](https://cecad365.sharepoint.com/:p:/r/sites/Splor/Documentos%20Compartilhados/General/@dcaf/@!projetos/@reestimativa/reestimativa_2023/apresentacoes/cofin/2023-01-05_sejusp/2023-01-05%20SEJUSP%2022%20x%2023.pptx?d=wd59431a5b4634f96b2ac699d5d3892ce&csf=1&web=1&e=pV9wvk&nav=eyJzSWQiOjk2MywiY0lkIjo2ODYxODQ2MjJ9).
> 
> Ps. A Microsoft [anunciou](https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/copilot-in-onedrive-a-new-wave-of-file-interaction/ba-p/4070738) que vai disponibilizar o Copilot no OneDrive no final de abril/2024, o que pode atender a demanda por busca nas apresentações e mais.

**Comment by labanca** [comment]
Snippet de busca:

`curl -X GET "localhost:9200/products/_search?pretty" -H 'Content-Type: application/json' -d' { "query": { "match": { "name": "t-shirt" } } }'`

**Comment by fjuniorr** [comment]
Finalizado com a descoberta que é possível gerar o link para o slide no sharepoint a partir do slide_id
