### ISSUE TITLE
Painel revisão qualitativa PPAG 

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#132]

**Comment by hslinhares** [comment]
- [ ] criar repositório dados ppag loa 2025;
- [ ] criar repostório para painel ppag 2025;
- [ ] substituir dados 2024 por 2025 na pág. inicial do painel;
- [ ] criar na pág. incial do painel uma coluna `atributos 2024 = 2025`, `True` or `False`;
- [ ] em `Dados Programa` e `Dados da Ação` deixar somente 2024 do lado esquerdo e 2025 do lado direito;
- [ ] retirar estados alternativos, ou seja, deixar a mesma seleção para os dois anos;
