### ISSUE TITLE
Armazém-GRP - receita - auxiliar DCAF na homologação

### ISSUE THREAD

**Issue by carloshob** [splor-mg/atividades#134]
Issue criado para registros das interações envolvendo a testagem e homologação do Armazém-GRP em relação ao universo receita, conforme demandado por @felipeduba em [Reunião Status SPLOR de 01/07/2024](https://github.com/splor-mg/reunioes/issues/55)

**Comment by carloshob** [comment]
## [09/10/2024] Reunião para Explicações Gerais

- Participantes: Marina Freitas, Leonardo Amorim, Laura e Carlos

### Ata 

- repassados o contexto das definições das variáveis de consulta no Armazém

- DCAF fará contato com Larissa para alinhamento de testes

**Comment by carloshob** [comment]
## Discussão Variável `Valor Efetivado Ajustado`

**Alinhamento SEF - pontos de atenção**

motivação - fundamentação legal vs sistema

> - (1) "vl-efet-ajust." não foi contemplado no Armazém GRP porque se entendeu que não vai ser usado"

> - (4) "não seria contemplado (...) porque de acordo com os Tribunais e as normas de contabilidade não fazia mais sentido - tinha que ser sempre do valor contabilizado"




conceito - operacionalização

> - (2) "era quando vc entrava no mês seguinte e conseguia fazer o registro para o mês anterior (...) a gente chamava de período de ajuste mensal"


> - (3) "as vezes tem ARRECADAÇÃO dentro do mês que não dá tempo de fazer todo REGISTRO dentro do mês"


> - (5) "o que foi contabilizado dentro do mês é o que está sendo realizado" - então as consultas serão baseadas no realizado


> - (6) "ao longo do ano o valor realizado poderia ter diferença, mas não no final do ano ele sempre tinha que fechar"



implicações de sistema

> - (7) "nessa parte de RECEITA CONSOLIDADA porque entendeu-se que os dados orçamentários poderiam ser utilizados da parte lá de cima EXECUÇÃO ORÇAMENTÁRIA DA RECEITA - que são grupos que qualquer MÓDULO pode utilizar"

**Comment by fjuniorr** [comment]
@carloshob o seu esforço está sendo durante as reuniões com a DCAF, certo? Em caso positivo, Vou fechar esse issue pra deixar mais claro que ele não está sendo "trabalhado".
