### ISSUE TITLE
Verificar necessidade do dado `Elemento origem DEA` retirado do armazém siafi histórico

### ISSUE THREAD

**Issue by hslinhares** [splor-mg/atividades#146]
A retirada do dado `Elemento origem DEA` do armazém siafi histórico está quebrando a leitura do script qlikview do rel. operacional.
Verifcar a necessidade do dado para, entrar em contato com prodemge para inserí-lo, ou modificar o script do qlikview para corrigir o problema da carga.

**Comment by hslinhares** [comment]
![image](https://github.com/user-attachments/assets/040edf6d-afee-4f92-a936-967220a19b04)

**Comment by gabrielbdornas** [comment]
> Opção por mudar o código do qlikview.
> 
> ver #146

@hslinhares, entrei aqui para entender melhor [este Issue](https://github.com/splor-mg/roperacional/issues/44) e, de fato, ajudou a entender. Só não entendi a referência que você incluiu para o próprio Issue. A ideia seria, por acaso, referenciar [este](https://github.com/splor-mg/roperacional/issues/44)?
