### ISSUE TITLE
Fazer extração e carga do conjunto da despesa no postgres

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#18]
@labanca usa o repo [postgresql-carga-despesa](https://github.com/splor-mg/postgresql-carga-despesa) pra essa tarefa. Já deixei lá o docker pra levantar o PostgreSQL e o pgAdmin per #14.

Apesar de aparentemente a [instalação no windows](https://www.postgresql.org/download/windows/) ser simples, vai ser conveniente poder "resetar" o banco de dados simplesmente deletando os volumes do docker associados ao respectivo container.

**Comment by labanca** [comment]
O código foi adaptado, restando a criação da Database automaticamente (sem usar o PgAdmin por exemplo).

Estou aprendendo a usar de SqlAlchemy para essa situação e para uso futuro em outros projetos. Vou subir um commit com o estado atual.

**Comment by labanca** [comment]
ERRO: psycopg2.errors.ActiveSqlTransaction: CREATE DATABASE cannot run inside a transaction block

investigando possível causa.

O postgres não cria a database automaticamente quando a conexão é feita da mesma forma que o Sqlite e o DuckDB. Ao pesquisar parece que ele não suporta comandos "IF NOT EXISTS" em "CREATE TABLE", então estou buscando uma forma de contornar essa limitação.
