### ISSUE TITLE
Incorporar aos scripts de carga de dados leitura de datapackages que descrevem as fontes

### ISSUE THREAD

**Issue by labanca** [splor-mg/atividades#21]

**Comment by fjuniorr** [comment]
@labanca ainda esta em elaboração mas se entendi bem o objetivo desse issue vale a pena você já passar o olho [nessa nota](https://github.com/splor-mg/notas/pull/9).

**Comment by fjuniorr** [comment]
Duplicate of https://github.com/splor-mg/atividades/issues/7
