### ISSUE TITLE
Tutoriais software carpentry para onboarding Henrique

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#23]
@hslinhares instruções no repo https://github.com/splor-mg/handbook

**Comment by hslinhares** [comment]
Tópicos estudados em 10/05/23:

- [Introducing the Shell – The Unix Shell](https://swcarpentry.github.io/shell-novice/01-intro/index.html)
- [Navigating Files and Directories – The Unix Shell](https://swcarpentry.github.io/shell-novice/02-filedir/index.html)

**Comment by fjuniorr** [comment]
@hslinhares acho que isso aqui já terminou né?

**Comment by hslinhares** [comment]
@fjuniorr falta somente realizar o de `SQL` pra fechar.
