### ISSUE TITLE
Minutar decreto de competências da Assessoria de Dados

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#24]
Vou deixar sempre no primeiro comentário a versão mais atual das competências:

---

A Assessoria de Inteligência de Dados tem como competência propor a arquitetura de dados analíticos que garanta a qualidade e a disponibilidade das informações necessárias aos processos de tomada de decisão da Subsecretaria de Planejamento e Orçamento, com atribuições de:

- planejar o modelo de dados de suporte aos processos de inteligência analítica;
- desenvolver sistemas e ferramentas no âmbito de suas competências;
- promover a transparência ativa, no âmbito de suas competências, por meio da divulgação de informações de interesse coletivo ou geral em formatos abertos, estruturados e legíveis por máquina;
- identificar, em colaboração com às unidades administrativas da Subsecretaria de Planejamento e Orçamento, oportunidades de aplicação de sistemas de apoio à decisão e de inteligência analítica;
- capacitar e oferecer assessoria técnica às unidades administrativas da Subsecretaria de Planejamento e Orçamento na utilização de técnicas e ferramentas de análise de dados.

**Comment by labanca** [comment]
Seguem algumas sugestões @fjuniorr:

A Assessoria de Inteligência de Dados tem como competência **_propor e gerir projetos e processos de dados analíticos_**, que garantam a qualidade e a disponibilidade das informações necessárias à tomada de decisão da Subsecretaria de Planejamento e Orçamento, com atribuições de:

I - planejar e gerir o modelo de dados de suporte aos processos de inteligência analítica; 👍 

II - gerenciar a infraestrutura tecnológica necessária para a gestão **_dos referidos processos e projetos_**;

III - desenvolver sistemas e ferramentas no âmbito de suas competências; 👍 

IV - promover a transparência ativa, no âmbito de suas competências, por meio da divulgação de informações de interesse coletivo ou geral em formatos abertos, estruturados e legíveis por máquina; 👍 

V - identificar, em colaboração com às unidades administrativas da Subsecretaria de Planejamento e Orçamento, oportunidades de aplicação de sistemas de apoio à decisão e de inteligência analítica; 👍 

VI - capacitar **_e oferecer assessoria técnica_** às unidades administrativas da Subsecretaria de Planejamento e Orçamento na utilização de técnicas e ferramentas de análise de dados.

**Comment by hslinhares** [comment]
👍 

na minha opinião a redação está clara e objetiva, perpassando por todas as atribuições e atividades que se espera da assessoria. Mais concisa e bem escrita que as competências dos outros órgãos que estão como exemplo.
Em um primeiro momento sento a falta das palavras "fomentar" e/ou "promover" o uso de ferramentas, no inciso "capacitar e oferecer assessoria técnica às unidades administrativas ...". Para dar ideia de uma posição proativa da assessoria nessa atividade. Mas o ajuste é opcional porque isso está implícito no inciso.

**Comment by fjuniorr** [comment]
> A Assessoria de Inteligência de Dados tem como competência **_propor e gerir projetos e processos de dados analíticos_**, que garantam a qualidade e a disponibilidade das informações necessárias à tomada de decisão da Subsecretaria de Planejamento e Orçamento, com atribuições de:

@labanca  "arquitetura de dados analíticos" de fato é um termo amplo por causa da expressão arquitetura. 

__Não faz parte das competências da Assessoria a gestão da arquitetura de dados dos sistemas transacionais como SIGPLAN e SISOR__ que indiretamente também garantem a "qualidade e a disponibilidade das informações necessárias aos processos de tomada de decisão"

No entanto acho "projetos e processos de dados analíticos" um termo confuso (eg. o que seriam processos de dados analíticos?) então vou optar por manter "arquitetura de dados analíticos" .

> Em um primeiro momento sinto a falta das palavras "fomentar" e/ou "promover" o uso de ferramentas, no inciso "capacitar e oferecer assessoria técnica às unidades administrativas ...". Para dar ideia de uma posição proativa da assessoria nessa atividade. Mas o ajuste é opcional porque isso está implícito no inciso.

---

@hslinhares eu gosto de ideia mas no mesmo inciso acho que ficam verbos demais porque uma das competências atomizadas[^20230426T125610] seria "promover às unidades administrativas da Subsecretaria de Planejamento e Orçamento na utilização de técnicas e ferramentas de análise de dados"

Dá pra falar que a posição proativa já está de certa forma no inciso V?

> V - identificar, em colaboração com às unidades administrativas da Subsecretaria de Planejamento e Orçamento, oportunidades de aplicação de sistemas de apoio à decisão e de inteligência analítica; 



[^20230426T125610]: Essa atomização está explicada no vídeo [LGPD CGE/MG - Técnica "Atomização de Critérios de Auditoria" para a Gestão de Riscos - YouTube](https://www.youtube.com/watch?v=RbSkBsJ72BI)

**Comment by labanca** [comment]
> No entanto acho "projetos e processos de dados analíticos" um termo confuso (eg. o que seriam processos de dados analíticos?) então vou optar por manter "arquitetura de dados analíticos" .

Concordo que pode ficar confuso, mas quis retirar a palavra "arquitetura" justamente por ser ampla demais, como você mesmo falou, e para não dar a entender que cuidar de computadores e servidores da subsecretária " qualidade e a disponibilidade das informações necessárias" estaria dentro disso.


> Não faz parte das competências da Assessoria a gestão da arquitetura de dados dos sistemas transacionais como SIGPLAN e SISOR que indiretamente também garantem a "qualidade e a disponibilidade das informações necessárias aos processos de tomada de decisão"

Isso é um comentário para aqui somente ou alguma alteração na minuta seria feita nesse sentido também?
No caso dos termos que propus, **projetos** seria o que estamos fazendo agora e quando colocados em produção se tornariam **processos**. Tentei dizer que cuidaríamos somente de nossas criações, mas esse meu entendimento desses dois termos pode estar defasado.

**Comment by fjuniorr** [comment]
> Isso é um comentário para aqui somente ou alguma alteração na minuta seria feita nesse sentido também?

Só para aqui. Colocar o que não é competência em decreto é complicado.

> No caso dos termos que propus, **projetos** seria o que estamos fazendo agora e quando colocados em produção se tornariam **processos**. Tentei dizer que cuidaríamos somente de nossas criações, mas esse meu entendimento desses dois termos pode estar defasado.

Saquei. Vou deixar arquitetura por preferência! :sweat_smile:

**Comment by fjuniorr** [comment]
Sobre a atribuição

> gerenciar a infraestrutura tecnológica necessária para a gestão de dados analíticos;

o @labanca tinha questionado via Whatsapp:

> [11:14, 26/04/2023] Andrey Labanca: se der a enteder que cuidar de hardware e servidor e responsabilidade nossa, vc nao ve problema?
> [12:00, 26/04/2023] Francisco Alves: Hardware e servidor que for usado pra suportar os “dados analíticos” tem que ser. 

Acho que o meu raciocínio estava incompleto.

_Se_ a SPLOR fizer gestão contratual e administração de infra (igual faz hoje), então faz sentido que essa competência seja da Assessoria de Dados e não das unidades (eg. DCPPN, DCAF).

Mas, seguindo a mesma lógica que resultou na criação da Superintendência Central de Gestão de Sistemas Corporativos, faz sentido que a parte contratual seja centralizada na SEPLAG (eg. uma única licitação para contratação de servidores virtualizados) e a Assessoria de Dados faça as vezes de área de negócio apontando as necessidades (eg. indicar que é necessário um servidor windows para instalação de qlikview server; indicar o volume de dados que será armazenado; etc)

Uma nova sugestão poderia ser:

> gerenciar a infraestrutura tecnológica necessária para a gestão de dados analíticos __em parceria com a unidade responsável pela política de tecnologia da informação no âmbito da Seplag__;

mas agora estou em dúvida se de fato faz sentido manter esse item.

**Comment by fjuniorr** [comment]
Perguntei pro chatGPT quais atividades concretas podem estar incluídas na competência de:

> gerenciar a infraestrutura tecnológica necessária para a gestão de dados analíticos

Ele respondeu:

> 1. Avaliação e seleção de ferramentas e plataformas: Identificar, avaliar e selecionar as ferramentas e plataformas mais adequadas para coleta, processamento, armazenamento, análise e visualização de dados.
> 2. Implementação e configuração de sistemas: Instalar, configurar e manter sistemas de gerenciamento de banco de dados, plataformas de análise e ferramentas de visualização, bem como sistemas de processamento de big data e soluções de machine learning.
> 3. Gestão de armazenamento e backup de dados: Implementar estratégias de armazenamento e backup de dados, garantindo a disponibilidade, integridade e recuperação dos dados em caso de falhas ou perdas.
> 4. Administração de servidores e redes: Monitorar e gerenciar servidores, redes e dispositivos relacionados, assegurando o desempenho, a segurança e a escalabilidade da infraestrutura tecnológica.
> 5. Segurança da informação: Estabelecer políticas e práticas de segurança, incluindo criptografia, controle de acesso e monitoramento, para proteger a confidencialidade, integridade e disponibilidade dos dados.
> 6. Otimização de desempenho: Monitorar e analisar o desempenho dos sistemas e da infraestrutura, identificando gargalos e implementando melhorias para garantir a eficiência e a velocidade das operações de análise de dados.
> 7. Atualização e manutenção de software e hardware: Planejar e executar atualizações e manutenções periódicas de software e hardware, garantindo a compatibilidade, estabilidade e desempenho dos sistemas.
> 8. Suporte técnico e capacitação: Prover suporte técnico aos usuários da infraestrutura tecnológica, bem como capacitar e treinar equipes na utilização das ferramentas e plataformas de análise de dados.
> 9. Gestão de licenças e contratos: Administrar licenças de software, contratos de serviços e parcerias com fornecedores, assegurando o cumprimento dos termos e a continuidade das operações.
> 10. Elaboração de políticas e procedimentos: Desenvolver e implementar políticas e procedimentos relacionados à gestão da infraestrutura tecnológica, garantindo a conformidade com as normas e regulamentações aplicáveis.

Isso clarificou o meu raciocínio de que entre as responsabilidades tradicionais de desenvolvimento, operações e infraestrutura somente desenvolvimento (e um pouco de operações via práticas DevOps) devem ser competência da Assessoria.

Removi a atribuição de "gerenciar a infraestrutura tecnológica necessária para a gestão de dados analíticos" e os verbos "gerir".

**Comment by labanca** [comment]
Como ficou a versão final @fjuniorr ?

**Comment by labanca** [comment]
> A nossa sugestão enviada pra consolidação final foi essa (tb tá atualizada no primeiro comentário do issue):

Costume de sempre ir pro final da thread. Ainda aprendendo git .

Versão final sanou todos meus receios iniciais. Ficou ótimo!

**Comment by fjuniorr** [comment]
Como a demanda do issue era trabalhar na minuta estou considerando essa atividade finalizada.

**Comment by fjuniorr** [comment]
Para registro as competências publicadas no [Decreto nº 48.636, de 19/06/2023](https://www.almg.gov.br/legislacao-mineira/texto/DEC/48636/2023/) foram:

> Art. 36 – A Assessoria de Inteligência de Dados tem como competência propor a arquitetura de dados analíticos que garanta a qualidade e a disponibilidade das informações necessárias aos processos de tomada de decisão da Subsecretaria de Planejamento e Orçamento, com atribuições de:
> 
> I – planejar o modelo de dados de suporte aos processos de inteligência analítica;
> 
> II – desenvolver sistemas e ferramentas no âmbito de suas competências;
> 
> III – promover a transparência ativa, no âmbito de suas competências, por meio da divulgação de informações de interesse coletivo ou geral em formatos abertos, estruturados e legíveis por máquina;
> 
> IV – identificar, em colaboração com às unidades administrativas da Subsecretaria de Planejamento e Orçamento, oportunidades de aplicação de sistemas de apoio à decisão e de inteligência analítica;
> 
> V – capacitar e oferecer assessoria técnica às unidades administrativas da Subsecretaria de Planejamento e Orçamento na utilização de técnicas e ferramentas de análise de dados.
>
