### ISSUE TITLE
Investigar grupo zero no consulta de aprovação de cota orçamentária no armazém

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#34]
Além disso o grupo de despesa está zerado:

![image](https://github.com/splor-mg/atividades/assets/4969445/bf1b022f-e539-4922-9ead-2df726c9b206)

@hslinhares investiga, relata o problema e a solução aqui e avisa pro Pedro quando estiver solucionado.

**Comment by hslinhares** [comment]
@fjuniorr verifiquei as bases do relatório operacional e constatei que o erro apresentado não é do aplicativo qlikview, mas sim da própria base do armazém, que está retornando grupo de despesa 0 na base de aprovação de cota orçamentária:
![image](https://github.com/splor-mg/atividades/assets/43452663/d3396ace-0691-4f7e-8747-f1fa0bf6fc8c)

**Comment by fjuniorr** [comment]
@hslinhares abre um chamado pra eles no [Fale com o Tesouro](http://www.fazenda.mg.gov.br/tesouro-estadual/tesouro-estadual/fale-com-o-tesouro-00001/):

![Secretaria_de_Estado_de_Fazenda_de_Minas_Gerais_-_SEF_MG_-_SEF_MG](https://github.com/splor-mg/atividades/assets/4969445/d6e3463b-7b8c-4ef8-9db6-32ceccafbbbc)

Acho que vale a pena criar uma consulta do zero pra reproduzir o erro e eventualmente compartilhar com eles.

**Comment by hslinhares** [comment]
Segue o chamado aberto:

Prezados, boa tarde

Trabalho na Assessoria de Inteligência de Dados da Subsecretaria de Planejamento e Orçamento da SEPLAG  e utilizamos o armazém SIAFI para consultas diárias.
Constatamos que consulta realizada no universo SIAFI_Sistema_Integrado_de_Administração_Financeira com dados da pasta APROVAÇÃO DA COTA ORÇAMENTÁRIA está retornando com erro.
Nesta consulta está retornando a classificação orçamentária por natureza de despesa, [Grupo Despesa - Código] igual a 0, o que não existe.
Foi salvo uma amostra da consulta na pasta publica, SUPORTE-SIAFI, ASSESSORIA_SPLOR/SEPLAG, a consulta cota-item-data_2023, em que consta filtro [Grupo Despesa - Código] = 0 na tabela gerada em que é possível verificar o erro relatado.
Também consta anexa print do erro encontrado.
Desde já agradeço e para explicações adicionais que se façam necessárias estou à disposição no 9 8571-1690.

![print_erro](https://github.com/splor-mg/atividades/assets/43452663/e492ee45-45e9-43f5-b6c9-549dfb7a4e11)

**Comment by hslinhares** [comment]
![image](https://github.com/splor-mg/atividades/assets/43452663/3f2eefba-5443-4cae-8eec-1b986701b602)

**Comment by hslinhares** [comment]
@fjuniorr Verifiquei que o problema foi solucionado. A consulta não mais retorna grupo de despesa 0

![image](https://github.com/splor-mg/atividades/assets/43452663/94d2cc76-8d78-4e43-9517-669af1a9e286)
