### ISSUE TITLE
Investigar diferença entre valores de empenho entre as bases "confererencia", "execucao_2023-04" e "execucao_2023-05" do roperacional

### ISSUE THREAD

**Issue by hslinhares** [splor-mg/atividades#38]
Erro não usual. 
A base conferência serve para conferir se o roperacional está consolidando corretamente as bases.

Em dois dias seguindo foi verificada diferença no valor empenhado entre as bases "conferencia.xlx" e "execucao_2023-04" e  "execucao_2023-05" que chegam por e-mail. Provavelmente pelo horário em que são geradas, o armazém está retornando valores distintos.

**Comment by hslinhares** [comment]
Foi aberto o seguinte chamado no fale com o tesouro:

Para realizar o seu atendimento necessitamos dos seguintes dados:

Unidade Orçamentária - Código/Sigla (se aplicável): 1501/SEPLAG
Unidade Executora - Código (se aplicável): n/a
Nº do documento registrado (se aplicável) n/a


Gentileza detalhar sua demanda/dúvida

Prezados, boa tarde

Trabalho na Assessoria de Inteligência de Dados da Subsecretaria de Planejamento e Orçamento da SEPLAG e utilizamos o armazém SIAFI para consultas diárias.
Constatamos que a consulta no universo SIAFI_Sistemas_Integrado_de_Administração_Financeira passou a retornar dados aparentemente incorretos para os meses de abril e maio de 2023.
Foi salvo  na pasta publica, SUPORTE-SIAFI, ASSESSORIA_SPLOR/SEPLAG, as consultas "execucao_2023" e "execucao_consolidado" para verificação do erro.
É possível verificar que na consulta "execucao_consolidado" os valores da despesa empenha nos meses 4 e 5 de 2023 diferem da consulta "execucao_2023".
A diferença entre elas é que na "execucao_2023" existem diversas dimensões na consulta que de uso no cotidiano no nosso setor. Porém , para facilitar a verificação do erro elas foram retiradas do relatório final .
Parece que alguma dimensão contida na pesquisa está interferindo no resultado do valor da despesa empenhada, já que na consulta "execucao_consolidado" há somente "Ano de Exercício" e "Mês-Numérico".
Desde já agradeço e para explicações adicionais que se façam necessárias estou à disposição no 9 8571-1690.

![execucao_2023](https://github.com/splor-mg/atividades/assets/43452663/39911f07-6b95-4915-86ca-76398048aa1c)
![execucao_consolidado](https://github.com/splor-mg/atividades/assets/43452663/8aa69efd-d6e3-456d-92bb-9890849872bb)

**Comment by hslinhares** [comment]
<html>
<body>


Prezado(a) Henrique de Souza Linhares,Ref. a mensagem: 1.399.354 - SIAFI - MG - Demais atendimentos > Armazém de Informações SIAFI-MGHenrique, bom dia!Estamos verificando o motivo de ao inserir o objeto de resultado "Licitação - descrição da Modalidade" na consulta Execução_2023 está retornando valor incorreto.Assim que solucionado informaremos.Atenciosamente,Tadeu LageDiretoria Central de Governança do Sistema
--
Atenciosamente,
SEF AtendeTES/DCGS10 - TESOURO - Sistema de Administração Financeira


</body>
</html>

**Comment by hslinhares** [comment]
Como o objeto "Licitação - descrição da modalidade" não está sendo utilizada no roperacional, foi retirada da consulta do armazém para regularizar os valores da base de execução.
Aguardando retorno final do Fale com o Tesouro para fechamento do Issue.

**Comment by fjuniorr** [comment]
A equipe de suporte do Armazém SIAFI não entrou em contato mas vamos optar por fechar esse issue tendo em vista o volume de issues abertos.
