### ISSUE TITLE
Fazer extração e carga do conjunto da despesa no duckdb

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#4]
## Links

- https://dados.mg.gov.br/dataset/despesa

**Comment by labanca** [comment]
[Repositório](https://github.com/splor-mg/duckdb-carga-despesa) criado.

Tabelas já são criadas e dados do portal dados.mg carregados pelo script [duckdb-carga-despesa.ipynb](https://github.com/splor-mg/duckdb-carga-despesa/blob/14d3275b6fa734fc6740df48dd96d29111d67157/duckdb-carga-despesa.ipynb), porém a concatenação dos dados de faturamento está dando estouro de memória. 

Estou procurando um jeito mais eficiente de fazer isso. Provavelmente será por meio de gravação em disco a cada arquivo novo concatenado ao invés de carregar tudo para a memória.

**Comment by labanca** [comment]
@fjuniorr Mudei para execução para script Python e tudo funcionou. Todos os arquivos do dataset de despesa são carregados e a base DuckDB é criada em disco. 

As tabelas fato que eram separadas por ano todos são concatenadas em uma só tabela contendo todos os anos. 

Creio que isso encerra as demandas deste issue do DuckDB.

**Comment by fjuniorr** [comment]
@labanca sempre que possível o revisor deve tentar executar o código. Isso significa que faz sentido a gente investir em automatizar ao máximo as tarefas, especialmente aquelas que tem possibilidade de reuso como essa. No caso concreto estou falando dos scripts para download em massa e unzip dos arquivos.

Das [duas opções](https://github.com/splor-mg/plano-atividades/issues/5#issuecomment-1477755521) que eu havia dado para o download, o [`dpckan dataset get`](https://github.com/transparencia-mg/dpckan/issues/190) está com problemas, mas o [ckanapi](https://github.com/ckan/ckanapi#bulk-dataset-and-resource-export---datapackagejson-format) funciona com:

```bash
ckanapi dump datasets --remote https://dados.mg.gov.br/ --datapackages=datasets despesa
```

Um outro ponto é pra deixarmos em notebooks somente código para exploração e explicação. Falo isso nem por causa do problema concreto de memória que você teve, mas porque fica mais fácil a gente "rodar em produção" e adicionar testes se o código já estiver em scripts/pacotes. 

Por fim, senti falta de um único ponto de entrada pra execução do fluxo inteiro (tirando instalação de dependências). No caso concreto isso poderia ser um Makefile com um target `make all` que fizesse o download, unzip e carga no duckdb.

Vou reabrir o issue pra você atacar essas questões. 

Ps. Se encontrar problemas com os dados, vá abrindo issues no repo https://github.com/transparencia-mg/age7. Por exemplo https://github.com/transparencia-mg/age7/issues/193

**Comment by labanca** [comment]
@fjuniorr encontrei um erro nos dados. O arquivo dm_empenho_desp_2016.csv.gz está vazio. Amanhã vou abrir um issue com o pessoal do Transparência. Adicionei um tratamento de exceção para que o script não de erro (a tabela em branco gera erro de tipos de dados, pois os headers viram uma linha que conflita com os tipos das colunas já existentes da tabela sendo concatenada).

Subi uma versão com automação. Queria uma revisão de código, acho que está muito simplório ainda, e acho que minhas escolhas de nomes pros Phonys não foram boas.

**Comment by fjuniorr** [comment]
> @fjuniorr encontrei um erro nos dados. O arquivo dm_empenho_desp_2016.csv.gz está vazio. Amanhã vou abrir um issue com o pessoal do Transparência.

Vamo acompanhar no https://github.com/transparencia-mg/age7/issues/193#issuecomment-1506827180. 

> Subi uma versão com automação. Queria uma revisão de código, acho que está muito simplório ainda, e acho que minhas escolhas de nomes pros Phonys não foram boas.

Vou dar uma olhada sim!

**Comment by labanca** [comment]
@hslinhares se tiver como tenta baixar e executar o código deste repositório, no escuro mesmo. Já vai ser um bom teste de usabilidade. Se você tiver alguma dúvida ou erro, só falar comigo que vamos ajustando.

**Comment by hslinhares** [comment]
@labanca consegui executar corretamente o código em minha máquina e baixar todos os arquivos .csv.

Algumas considerações:

- Informar que a etapa "Criar ambiente virtual do projeto" só precisa ser feita na primeira vez em que fizer o clone e rodar o projeto, não sendo necessário nas demais vezes.

- As etapas "Criar arquivo de requerimentos" e "Abrir o arquivo e inserir os seguintes requerimentos" não precisam ser feitas pelo usuário do projeto, uma vez que o arquivo já consta no projeto e é baixado quando fazemos o clone.

- O arquivo makefile foi modificado e comitado. O comando do make all foi simplificado, passando a ter o make run e o make all como dependências, retirando a necessidade de reescrever o comando dos mesmos.

**Comment by labanca** [comment]
Obrigado pelas sugestões!

Fiz as atualizações e realizei o commit no repositório.

**Comment by fjuniorr** [comment]
[IOException error with no further information · Issue #6956 · duckdb/duckdb](https://github.com/duckdb/duckdb/issues/6956)
