### ISSUE TITLE
Publicação de Painel EPPGG

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#54]
> Estamos precisando publicar uma parte do Painel Sugesp destinada ao histórico de EPPGG’s em um link separado. É possível? Segue em anexo o arquivo contendo somente o que precisa ser publicado. Alterei o nome para Painel EPPGG para diferenciar do Painel Sugesp.

@hslinhares tem algum jeito de viabilizar isso sem usar novas licenças?

**Comment by hslinhares** [comment]
@fjuniorr o qlikview utiliza licença por documento, possibilitando somente um link para cada projeto .qvw  

O que eu já fiz foi ler um .qvw em outro .qvw, Assim tinha 2 painéis dentro do mesmo link, separados por abas utilizando uma única licença.

De acordo a política de licensas do qlikview:

*"Licensing Policy
QlikView offers two types of user licensing:

Named User License - license per named user, with no limit on the number of available documents.
Document License – license with the access type of user / document when the user has access only  to a single document.
QlikView offers two main types of server licenses:

Small Business Edition Server, which has a limit on the number of named users attached to it - no more than 25, as well as the number of licenses "user / document" - the limit of a 100. Thus, Small Business Edition Server may be run by up to 125 users: 100 of them with access to a single document at the same time, and 25 of them with access to any of the documents.
Enterprise Edition Server is used for an unlimited number of users to solve more complex problems. The minimum number of named users using QlikView Enterprise Edition is 10, the maximum number is unlimited. The minimum number of licenses "user / document" using QlikView Enterprise Edition is 100, the maximum number is unlimited.*

**Comment by fjuniorr** [comment]
> O que eu já fiz foi ler um .qvw em outro .qvw, Assim tinha 2 painéis dentro do mesmo link, separados por abas utilizando uma única licença.

Não consegui visualizar a interface/usabilidade disso. Tem um screenshot aí?
