### ISSUE TITLE
Criar data package privado para controle das atribuições das licenças do qlikview

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#55]
Aparentemente temos: 

- 14 Named User Call
- 40 Document Call

@hslinhares crie um repo privado e faça um levantamento dos dados no servidor (usando tanto os dados da planilha de controle quando do painel do QMC de licenças).

**Comment by fjuniorr** [comment]
> > Is there a way to automatically collect the assignments of qlikview document calls licences?
> 
> As of my last update, QlikView does not offer an automated feature to collect assignments of Document CALs (Client Access Licenses). 
> 
> Typically, you can view and manage Document CALs from QlikView Management Console (QMC). This manual process requires a QlikView administrator to navigate to the QMC, go to Documents > User Documents > [Your Document] > CALs > Assigned CALs.
> -- chatGPT

Não verifiquei a veracidade.

**Comment by hslinhares** [comment]
@fjuniorr seguindo a [resposta do ChatGPT](https://github.com/splor-mg/atividades/issues/55#issuecomment-1613082777)

Verifica-se que no servidor http:200.198.9.184 há 9 licenças Named User Call em uso de um total de 14 e 39 Document Call de um total de 40.

![image](https://github.com/splor-mg/atividades/assets/43452663/4863df00-3237-458a-8198-88e7323da96e)

![image](https://github.com/splor-mg/atividades/assets/43452663/ba831c2b-f6f9-4041-b6b2-943b9a11a5d1)
