### ISSUE TITLE
Criar datapackage para painel OBZ

### ISSUE THREAD

**Issue by labanca** [splor-mg/atividades#58]
Criar datapackage nos moldes do [ppag-planejamento](https://github.com/splor-mg/ppag-planejamento-dados) para o [OBZ-dados](https://github.com/splor-mg/obz-dados). Template em https://github.com/splor-mg/datapackage-template/tree/dev

Esta atividade deve ser feita de maneira célere com objetivos didáticos.

Um datapackage com *n* resources pra *n* orgãos e um mesmo arquivo de schema (obz.yaml) para todos os resources (validate do frictionless vai mostrar os órgãos que fizeram modificações).

**Comment by fjuniorr** [comment]
@labanca fiz uma evolução importante na estrutura discutida em https://github.com/splor-mg/atividades/issues/50#issuecomment-1611491487

**Comment by fjuniorr** [comment]
@labanca hoje participei da [Frictionless Data Community Call](https://frictionlessdata.io/blog/2023/06/05/community-call-fastetl/) e eles falaram sobre "strange datasets :ghost: and how to describe them". Pra pular a primeira linha a gente pode usar a propriedade [headerRows](https://framework.frictionlessdata.io/docs/framework/dialect.html#header-rows)

```yaml
    dialect:
      excel:
        sheet: 'BASE OBZ'
        headerRows:
          - 2
```

A [documentação](https://framework.frictionlessdata.io/docs/framework/dialect.html#header-rows) não é tão clara mas faz sentido:

> If header is True which is default, this parameters __indicates where to find the header row__ or header rows for a multiline header.

Antes eu estava tentando usar a `commentRows` [documentada](https://framework.frictionlessdata.io/docs/framework/dialect.html#comment-rows) como "a list of rows to ignore".

**Comment by fjuniorr** [comment]
Outra coisa da especificação que pode ser útil para as validações é usar a `constraint` [`pattern`](https://specs.frictionlessdata.io/table-schema/#constraints), que deixa especificar uma regex pro campo. [Por exemplo](https://regexr.com/) `\d{2} - .*`:

![20230629T162658](https://github.com/splor-mg/atividades/assets/4969445/31e8d71e-0f52-4e9d-ae4c-c289ec75f6bc)

**Comment by fjuniorr** [comment]
@labanca te mandei ontem via email duas planilhas de OBZ que vieram dos órgãos.

Prioriza por favor esse issue no lugar do splor-mg/reestimativa-dados#2 porque em última hipótese a gente ainda pode nos primeiros dias rodar a atualização manualmente nos nossos computadores.

**Comment by fjuniorr** [comment]
@labanca a estrutura correta é:

```yaml
dialect:
  excel:
    sheet: BASE OBZ
  headerRows: # mesmo nível da propriedade excel
    - 2
```

e não

```yaml
dialect:
  excel:
    sheet: 'BASE OBZ'
    headerRows:
      - 2
```

como eu [coloquei acima](https://github.com/splor-mg/atividades/issues/58#issuecomment-1613676655). Tem um [reprex aqui](https://github.com/splor-mg/datapackage-reprex/tree/main/20230629T110916).
