### ISSUE TITLE
Criar reprex para leitura de csv seguindo RFC4180 no PowerBI

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#68]
No projeto do painel tivemos problemas com isso porque o PowerBI não deixa especificar o separador decimal em [Csv.Document](https://learn.microsoft.com/en-us/powerquery-m/csv-document), usando as preferências regionais. 

Mas [essa resposta](https://stackoverflow.com/a/42387563/13259574) parece indicar que é possível configurar a preferência regionais em um `.pbix` específico (e não necessariamente do sistema operacional) via `Options` -> `Current File` -> `Regional Settings` -> `Locale`.

**Comment by labanca** [comment]
Após o arquivo carregado existe a opção a seguir para utilizar um `locale` ao trocar o tipo de dado da coluna:

![image](https://github.com/splor-mg/atividades/assets/7211451/4d06ffb9-c567-48a5-bbdf-ab8f5d841793)

**Comment by fjuniorr** [comment]
@labanca ótimo saber que a gente tem flexibilidade de escolher a configuração por coluna!

Ainda vale a pena checar a opção `Options` -> `Current File` -> `Regional Settings` -> `Locale` para um arquivo pbix específico para os casos em que todas as fontes de dados estejam no padrão americano.

**Comment by fjuniorr** [comment]
Além disso parece que o pbix no repo reprex está vazio:

![image](https://github.com/splor-mg/atividades/assets/4969445/cdf15026-0f38-4c8e-a516-6867ad3f5ba4)

**Comment by labanca** [comment]
> Além disso parece que o pbix no repo reprex está vazio:

Corrigido em https://github.com/splor-mg/reprex/commit/25eddc4aaf12c1aacee17cbb672da6deff3c076e

**Comment by labanca** [comment]
reprex criado em https://github.com/splor-mg/reprex/commit/dbe07fb7f5eb00571004bda24357b1deb9049f45

`Options `->` Current File` -> `Regional Settings` -> `Locale`:

![image](https://github.com/splor-mg/atividades/assets/7211451/e4217f95-5b66-45e2-89ab-ab515878877f)

Arquivo CSV separado por vírgulas com decimal ponto sem precisar de especificar `locale` para a coluna:

![image](https://github.com/splor-mg/atividades/assets/7211451/e5472441-25cd-4b68-ab1a-fa781ec9e240)

Conversão correta para tipo:

![image](https://github.com/splor-mg/atividades/assets/7211451/cc2891d4-b45a-4a46-9e42-edce86eae03a)

Se puder tentar abrir o arquivo e ver seu comportamento @fjuniorr. Reabrindo aqui a conversão correta de decimal se mantinha.

**Comment by fjuniorr** [comment]
Abri e funcionou mantendo a configuração da locale somente pra esse arquivo! Duas coisas pra finalizar:

- O arquivo `reprex/20230904T200115/CurrentFile-Locale.pbix` pode ficar dentro do `reprex/20230901T171459` também porque tem o mesmo tema e usam os mesmos arquivos de dados
- Cria um item pra esse reprex na lista https://github.com/splor-mg/reprex#reprex

**Comment by labanca** [comment]
> Abri e funcionou mantendo a configuração da locale somente pra esse arquivo! Duas coisas pra finalizar:
> 
> * O arquivo `reprex/20230904T200115/CurrentFile-Locale.pbix` pode ficar dentro do `reprex/20230901T171459` também porque tem o mesmo tema e usam os mesmos arquivos de dados
> * Cria um item pra esse reprex na lista https://github.com/splor-mg/reprex#reprex

Realizado em: https://github.com/splor-mg/reprex/commit/fc6f137cdb3825b49127b81e1137a71251980a7b

**Comment by labanca** [comment]
Futuramente testar colunas com locales híbridos no mesmo arquivo em padrão americano e qualificador de texto em todas as colunas. Verificar se o separador decimal em padrão brasileiro irá conflitar com os separador de colunas do csv padrão americano.
