### ISSUE TITLE
atualização tabelas auxiliares de uo dos painéis ppag e sisor

### ISSUE THREAD

**Issue by hslinhares** [splor-mg/atividades#74]
tabelas atualizadas

@fjuniorr seria possível realizarmos a extração desses dados em csv do mesmo modo como extraímos as bases do sigplan e sisor ?

(https://www.orcamento.mg.gov.br/aoad/LtElemDespesa.jsp?Exec=S)

**Comment by fjuniorr** [comment]
Pode e faz todo sentido fazermos isso. Criei um issue dedicado https://github.com/splor-mg/atividades/issues/77.
