### ISSUE TITLE
abertura de chamado na prodemge sobre indiponibilidade de acesso ao servidor http://200.198.9.184/

### ISSUE THREAD

**Issue by hslinhares** [splor-mg/atividades#76]
chamado aberto via email hoje, 01/09/2023

**Comment by fjuniorr** [comment]
Teve alguma resposta @hslinhares?

**Comment by hslinhares** [comment]
- [] verificar alterações no servidor

**Comment by fjuniorr** [comment]
@hslinhares podemos fazer isso em conjunto na quarta feira na CAMG

**Comment by hslinhares** [comment]
@fjuniorr excluímos lixeira, pasta de downloads entre outros arquivos.

**Comment by hslinhares** [comment]
Constam 26 GB livres no disco C: de 119  e 114 GB no disco E: de 379 GB
Uma possível causa das instabilidades são os erros de script do painel qlikview da COF que permanecem durante a atualização dos demais painéis.

**Comment by fjuniorr** [comment]
Provavelmente não é espaço. De qualquer forma a gente tinha mandado essa mensagem no grupo dia 04/10:

> Gente, vamos deletar o conteúdo da pasta C:\Users\Administrator\Downloads no servidores na sexta feira.
> 
> Se alguém tiver necessidade de algum dos arquivos que está lá façam uma cópia até lá.

Não chegamos a fazer isso né? Pode deletar o conteúdo dela nos dois servidores.

Também entrei em contato com a COF no Teams e pedi pra investigarem o que está acontecendo nos scripts de carga.

**Comment by fjuniorr** [comment]
Em contato com a COF foi informado que o qlikview `cof_orcamento` (que é o que lança erros nos scripts de carga quase que diariamente) não é utilizado por eles.

@hslinhares eu te pedi pra desabilitar a atualização dele? Vc chegou a fazer?

**Comment by hslinhares** [comment]
@fjuniorr retirei a atualização sim. 
Não tinha no agendador do windows um .bat específico para o `cof_orcamento`, mas sim um `COF.bat`. 
Entrei na pasta da `COF` e vi que o arquivo `COF.bat` tem duas linhas, uma executa um arquivo `COF.qvw` e em outra `COF_orcamento.qvw`. Portanto o que fiz foi comentar neste arquivo `.bat`, com o comando `rem`, esta ultima linha.

**Comment by fjuniorr** [comment]
Então podemos fechar esse issue, certo?
