### ISSUE TITLE
Automação checklist conferência bases SIGPLAN/SISOR Planejamento para DCPPN

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#83]
https://github.com/splor-mg/checks-loa-ppag

**Comment by fjuniorr** [comment]
Alterei o nome do repositório para `checks-planejamento` e do pacote para `checks.planejamento`.  

Muito provavelmente teremos uma coleção de pacotes para processos diferentes, e eles podem ser nomeados:

- `checks-monitoramento`
- `checks-reestimativa`
- `checks-execucao`
- `checks-avaliacao`

Também podemos ter um pacote `checks` com funções gerais para todos os pacotes. No repositório podemos adicionar o sufixo `checks-r` ou `checks-py` se tivermos pacotes nas duas linguagens.

Testei algumas opções curtas sem usar ponto[^1] mas não gostei:

- `checkplan`
- `checkmon`
- `checkexec`
- `checkreest`
- `checkaval`

[^1]: No python o pacote teria que ser chamado `checks_planejamento`, mas o uso de `_` não é [recomendado](https://peps.python.org/pep-0008/#package-and-module-names). Mesmo o uso do `.` no R não é [recomendado](https://r-pkgs.org/workflow101.html#name-your-package:~:text=We%20recommend%20against%20using%20periods%20in%20package%20names%2C%20due%20to%20confusing%20associations%20with%20file%20extensions%20and%20S3%20methods.) pelo Hadley Wickham

**Comment by hslinhares** [comment]
Um comentário inicial. Não seria interessante substituir hífen por *underline* pela mesma questão que tratamos nos `datapackages`?

**Comment by hslinhares** [comment]
@fjuniorr eu achei mais intuitivo e melhor as opções longas, principalmente em um primeiro contato com as funções. Ficar mais verboso é mais fácil pra se guardar os comandos por se remeter diretamente aos nomes dos fluxos

**Comment by fjuniorr** [comment]
A primeira versão da conferência foi entregue. A segunda versão vai ser acompanhada via [projeto](https://github.com/orgs/splor-mg/projects/7) porque é um dos projetos que serão acompanhados pelo SPLOR nas reuniões gerenciais mensais.
