### ISSUE TITLE
Normalizar prefixo para colunas que representam valores monetários

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#86]
A primeira vez que eu vi a sugestão de usar prefixos para representar tipos de coluna foi em [Column Names as Contracts | Emily Riederer](https://emilyriederer.netlify.app/post/column-name-contracts/).

Durante a [implementação dos checks de consistência do SIGPLAN/SISOR](https://github.com/splor-mg/atividades/issues/83) a necessidade realmente apareceu porque preciso de fazer duas transformações[^20231201T122247] recorrentes depois de um join somente em colunas com valores monetários. 

Atualmente ao fazer join das bases do SISOR e SIGPLAN tenho que escrever:

```r
  df <- full_join(x, y, by = "UO_COD") |> 
        select("UO_COD" | ends_with("0") | ends_with("1") | ends_with("2") | ends_with("3")) |> 
        mutate(across(starts_with("VL_LOA_DESP"), replace_na)) |> 
        mutate(across(starts_with("VL_LOA_DESP"), pp)) |> 
        mutate(across(starts_with("vr_meta_orcamentaria"), replace_na)) |> 
        mutate(across(starts_with("vr_meta_orcamentaria"), pp))
```

E seria muito melhor escrever:

```r
  df <- full_join(x, y, by = "UO_COD") |> 
        select("UO_COD" | ends_with("0") | ends_with("1") | ends_with("2") | ends_with("3")) |> 
        mutate(across(starts_with("vlr_"), replace_na)) |> 
        mutate(across(starts_with("vlr_"), pp))
```

Minha opção seria por padronizar em `vlr_` no lugar de `vl_` ou `vr_`. O que você acha @hslinhares?

[^20231201T122247]: Quais sejam, substituir [`NA` por zero](https://github.com/splor-mg/checks-loa-ppag/blob/15a55e9b1485124fa51ee2b7a82f50bf8e61071a/R/utils.R#L26) e [formatar para apresentação](https://github.com/splor-mg/checks-loa-ppag/blob/15a55e9b1485124fa51ee2b7a82f50bf8e61071a/R/utils.R#L10)

**Comment by hslinhares** [comment]
@fjuniorr o prefiro `vlr` me parece tão intuitivo quanto `vl`, não vejo problemas em usarmos. Este prefixo realmente ajuda na organização e análise dos dados, ao separar os valores das características, principalmente em bases com muitas colunas.
