### ISSUE TITLE
Testar execução do `dpm install` no servidor qlikview

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#89]
Também fico curioso para saber se conseguimos rodar o spreadmart lá mas vamos deixar isso pra depois.

**Comment by hslinhares** [comment]
deu erro na instalação do `requirements.txt`
O `gitbash` do servidor não permite copiar mensagens, por isso printei

![image](https://github.com/splor-mg/atividades/assets/43452663/e07505e9-fe86-45b3-805c-338e52c675e7)

**Comment by fjuniorr** [comment]
Para referência a conversa sobre esse issue:

> [12/15 5:18 PM] Henrique de Souza Linhares (SEPLAG)
> os arquivos vao ser baixados no servidor diariamente por meio de um gitpull
> [12/15 5:18 PM] Henrique de Souza Linhares (SEPLAG)
> porem estão zipados o do armazem siafi dados
> [12/15 5:20 PM] Henrique de Souza Linhares (SEPLAG)
> onde entende que deveria entrar a etapa de descompressão? No mesmo makefile? em outro? ou fora do repositorio?
> [12/15 5:40 PM] Francisco Alves de Oliveira Júnior (SEPLAG)
> Vc chegou a olhar se o qlikview consegue ler csv.gz direto?
> [12/15 5:41 PM] Francisco Alves de Oliveira Júnior (SEPLAG)
> Vc tentou o dpm install e deu errado ou já foi direto pro git pull?
> [12/15 5:43 PM] Henrique de Souza Linhares (SEPLAG)
> eu tentei instalar o requirements.txt no servidor mas deu erro
> [12/15 5:44 PM] Henrique de Souza Linhares (SEPLAG)
> ao tentar baixar o dpm inclusive
> [12/15 5:44 PM] Henrique de Souza Linhares (SEPLAG)
> mas depois fui direto pro git pull
> [12/15 5:50 PM] Henrique de Souza Linhares (SEPLAG)
> realmente não aceita arquivos zipados
> [12/15 5:51 PM] Henrique de Souza Linhares (SEPLAG)
> nos foruns do qlikview a solução é exatamente executar o unzip pelo no CMD antes por meio de um .bat

@hslinhares é interessante deixar registrado nesse issue qual erro aconteceu. Depois pode fechar esse issue.
