### ISSUE TITLE
Criar listas com normativos de referência

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/atividades#99]
Essa lista deve ser composta por normativos distintos (idealmente um exemplar de cada tipo) para permitir a validação do mecanismo de recuperação de normativos.

**Comment by fjuniorr** [comment]
@carloshob essa tarefa está no âmbito do projeto [Feed alterações legislativas](https://github.com/orgs/splor-mg/projects/3/views/1?pane=info). 

coleta por favor alguns exemplos de normativos diferentes (eg. Lei, Decreto, Portaria, Instrução Normativo) provenientes de diários oficiais diferentes (União, Estado e Tribunal de Contas do Estado) como exemplos de legislação de interesse da área orçamentária com links (no diário oficial e em algum "agregador") para as publicações .

Se você souber exemplos reais de legislação que a gente deveria ter feito alguma coisa a respeito melhor ainda. Exemplo:

- Portaria STN nº 710/2021
- Portaria STN/MF Nº 1.561, de 8 dezembro de 2023 (recebi via newsletter e mandei pra DCAF)
- Decisão Normativa TCE 02/2023 (Felipe recebeu por whatsapp a informação de alteração)

**Comment by carloshob** [comment]
Levantamento amostral de arcabouço legal concluído.
